# Generated by Django 5.1.15 on 2026-02-19 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('interno', models.PositiveIntegerField(help_text='Número interno de la unidad (identificador operativo).', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='interno')),
                ('dominio', models.CharField(help_text='Dominio/patente. Se recomienda cargar en mayúsculas.', max_length=12, unique=True, verbose_name='dominio (patente)')),
                ('anio_modelo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='año modelo')),
                ('marca', models.CharField(max_length=40, verbose_name='marca (chasis)')),
                ('modelo', models.CharField(max_length=60, verbose_name='modelo (chasis)')),
                ('numero_chasis', models.CharField(help_text='Número/VIN del chasis (trazabilidad).', max_length=32, unique=True, verbose_name='número de chasis')),
                ('carroceria_marca', models.CharField(blank=True, default='', max_length=60, verbose_name='carrocería (marca)')),
                ('revision_tecnica_vto', models.DateField(blank=True, null=True, verbose_name='vencimiento revisión técnica')),
                ('tiene_gps', models.BooleanField(default=False, verbose_name='tiene GPS')),
                ('usa_biodiesel', models.BooleanField(default=False, verbose_name='usa biodiesel')),
                ('tipo_servicio', models.CharField(choices=[('MEDIA_DISTANCIA', 'Media Distancia'), ('URBANO', 'Urbano'), ('INTERURBANO', 'Interurbano')], default='MEDIA_DISTANCIA', max_length=20, verbose_name='tipo de servicio')),
                ('jurisdiccion', models.CharField(default='Chaco', help_text='Base principal. Puede ampliarse a futuro (otras provincias).', max_length=80, verbose_name='jurisdicción')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('TALLER', 'En taller'), ('BAJA', 'Baja')], default='ACTIVO', max_length=10, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'colectivo',
                'verbose_name_plural': 'colectivos',
                'ordering': ['interno'],
            },
        ),
    ]
