# Generated by Django 5.1.15 on 2026-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_alter_colectivo_numero_chasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colectivo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número/VIN del chasis (trazabilidad). Si no se conoce, dejar vacío.', max_length=32, null=True, verbose_name='número de chasis'),
        ),
        migrations.AddConstraint(
            model_name='colectivo',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_chasis__isnull', False)), fields=('numero_chasis',), name='uniq_colectivo_numero_chasis_if_not_null'),
        ),
    ]
