# Generated by Django 5.1.15 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_alter_colectivo_numero_chasis_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='colectivo',
            name='uniq_colectivo_numero_chasis_if_not_null',
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número/VIN del chasis (trazabilidad). Si no se conoce aún, dejar vacío.', max_length=32, null=True, unique=True, verbose_name='número de chasis'),
        ),
    ]
