# Generated by Django 5.1.15 on 2026-02-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_remove_colectivo_uniq_colectivo_numero_chasis_if_not_null_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colectivo',
            options={'ordering': ['interno'], 'permissions': [('can_import_colectivos', 'Puede importar colectivos (CSV)'), ('can_export_colectivos', 'Puede exportar colectivos (CSV)')], 'verbose_name': 'colectivo', 'verbose_name_plural': 'colectivos'},
        ),
    ]
