# Generated by Django 5.1.15 on 2026-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_alter_colectivo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colectivo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número/VIN del chasis. Puede cargarse después; si está vacío no se valida unicidad.', max_length=32, null=True, unique=True, verbose_name='número de chasis'),
        ),
    ]
