# Generated by Django 5.1.15 on 2026-02-24 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_partes_diarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='colectivo',
            name='matafuego_1_vto',
            field=models.DateField(blank=True, null=True, verbose_name='Matafuego 1 (venc.)'),
        ),
        migrations.AddField(
            model_name='colectivo',
            name='matafuego_2_vto',
            field=models.DateField(blank=True, null=True, verbose_name='Matafuego 2 (venc.)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_intervalo_km',
            field=models.PositiveIntegerField(blank=True, help_text='Cada cuántos km corresponde cambio de aceite (ej: 10000).', null=True, verbose_name='intervalo aceite (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_obs',
            field=models.TextField(blank=True, default='', help_text='Motivo si se cambió antes de tiempo, observaciones, etc.', verbose_name='observaciones aceite'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_ultimo_cambio_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha último cambio aceite'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_ultimo_cambio_km',
            field=models.PositiveIntegerField(blank=True, help_text='KM del último cambio de aceite.', null=True, verbose_name='último cambio aceite (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='anio_modelo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='año modelo'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='carroceria_marca',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='carrocerÃ\xada (marca)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='dominio',
            field=models.CharField(help_text='Dominio/patente. Se recomienda cargar en mayúsculas.', max_length=12, unique=True, verbose_name='dominio (patente)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_intervalo_km',
            field=models.PositiveIntegerField(blank=True, help_text='Cada cuántos km corresponde cambio de filtros (ej: 20000).', null=True, verbose_name='intervalo filtros (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_obs',
            field=models.TextField(blank=True, default='', help_text='Motivo si se cambió antes de tiempo, observaciones, etc.', verbose_name='observaciones filtros'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_ultimo_cambio_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha último cambio filtros'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_ultimo_cambio_km',
            field=models.PositiveIntegerField(blank=True, help_text='KM del último cambio de filtros.', null=True, verbose_name='último cambio filtros (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='interno',
            field=models.PositiveIntegerField(help_text='Número interno de la unidad (identificador operativo).', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='interno'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='jurisdiccion',
            field=models.CharField(default='Chaco', help_text='Base principal. Puede ampliarse a futuro (otras provincias).', max_length=80, verbose_name='jurisdicción'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='limpieza_ultima_fecha',
            field=models.DateField(blank=True, help_text='Fecha de la última limpieza registrada.', null=True, verbose_name='última limpieza'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='matafuego_ult_control',
            field=models.DateField(blank=True, help_text='Fecha del último control/recarga del matafuego.', null=True, verbose_name='último control de matafuego'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número/VIN del chasis. Puede cargarse después; si está vacÃ\xado no se valida unicidad.', max_length=32, null=True, unique=True, verbose_name='número de chasis'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='odometro_fecha',
            field=models.DateField(blank=True, help_text='Fecha en la que se registró el odómetro.', null=True, verbose_name='fecha odómetro'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='odometro_km',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje actual estimado. Se usa para alertas de mantenimiento.', null=True, verbose_name='odómetro (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='revision_tecnica_vto',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento revisión técnica'),
        ),
    ]
