# Generated by Django 5.1.15 on 2026-02-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0008_partes_diarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="colectivo",
            name="matafuego_vencimiento_2",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Vencimiento matafuego 2",
                help_text="Fecha de vencimiento del matafuego 2 de la unidad.",
            ),
        ),
    ]
