# Generated by Django 5.1.15 on 2026-02-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_colectivo_matafuego_1_vto_colectivo_matafuego_2_vto_and_more'),
        ('flota', '0009_colectivo_matafuego_2'),
    ]

    operations = [
    ]
