# Generated by Django 5.1.15 on 2026-02-24 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_merge_20260224_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_intervalo_km',
            field=models.PositiveIntegerField(blank=True, help_text='Cada cuÃ¡ntos km corresponde cambio de aceite (ej: 10000).', null=True, verbose_name='intervalo aceite (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_obs',
            field=models.TextField(blank=True, default='', help_text='Motivo si se cambiÃ³ antes de tiempo, observaciones, etc.', verbose_name='observaciones aceite'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_ultimo_cambio_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha Ãºltimo cambio aceite'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='aceite_ultimo_cambio_km',
            field=models.PositiveIntegerField(blank=True, help_text='KM del Ãºltimo cambio de aceite.', null=True, verbose_name='Ãºltimo cambio aceite (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='anio_modelo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='aÃ±o modelo'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='dominio',
            field=models.CharField(help_text='Dominio/patente. Se recomienda cargar en mayÃºsculas.', max_length=12, unique=True, verbose_name='dominio (patente)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_intervalo_km',
            field=models.PositiveIntegerField(blank=True, help_text='Cada cuÃ¡ntos km corresponde cambio de filtros (ej: 20000).', null=True, verbose_name='intervalo filtros (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_obs',
            field=models.TextField(blank=True, default='', help_text='Motivo si se cambiÃ³ antes de tiempo, observaciones, etc.', verbose_name='observaciones filtros'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_ultimo_cambio_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha Ãºltimo cambio filtros'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='filtros_ultimo_cambio_km',
            field=models.PositiveIntegerField(blank=True, help_text='KM del Ãºltimo cambio de filtros.', null=True, verbose_name='Ãºltimo cambio filtros (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='interno',
            field=models.PositiveIntegerField(help_text='NÃºmero interno de la unidad (identificador operativo).', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='interno'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='jurisdiccion',
            field=models.CharField(default='Chaco', help_text='Base principal. Puede ampliarse a futuro (otras provincias).', max_length=80, verbose_name='jurisdicciÃ³n'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='limpieza_ultima_fecha',
            field=models.DateField(blank=True, help_text='Fecha de la Ãºltima limpieza registrada.', null=True, verbose_name='Ãºltima limpieza'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='matafuego_1_vto',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del matafuego 1 de la unidad.', null=True, verbose_name='vencimiento matafuego 1'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='matafuego_2_vto',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del matafuego 2 de la unidad.', null=True, verbose_name='vencimiento matafuego 2'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='matafuego_ult_control',
            field=models.DateField(blank=True, help_text='Fecha del Ãºltimo control/recarga del matafuego.', null=True, verbose_name='Ãºltimo control de matafuego'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='NÃºmero/VIN del chasis. Puede cargarse despuÃ©s; si está vacÃ\xado no se valida unicidad.', max_length=32, null=True, unique=True, verbose_name='nÃºmero de chasis'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='odometro_fecha',
            field=models.DateField(blank=True, help_text='Fecha en la que se registrÃ³ el odÃ³metro.', null=True, verbose_name='fecha odÃ³metro'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='odometro_km',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje actual estimado. Se usa para alertas de mantenimiento.', null=True, verbose_name='odÃ³metro (km)'),
        ),
        migrations.AlterField(
            model_name='colectivo',
            name='revision_tecnica_vto',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento revisiÃ³n tÃ©cnica'),
        ),
    ]
