# Generated by ChatGPT patch

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0011_alter_colectivo_aceite_intervalo_km_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalidaProgramada",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado el")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado el")),
                ("salida_programada", models.DateTimeField(verbose_name="salida programada")),
                ("llegada_programada", models.DateTimeField(blank=True, null=True, verbose_name="llegada programada")),
                ("salida_real", models.DateTimeField(blank=True, null=True, verbose_name="salida real")),
                ("llegada_real", models.DateTimeField(blank=True, null=True, verbose_name="llegada real")),
                ("tipo", models.CharField(choices=[("NORMAL", "Normal"), ("ESPECIAL", "Especial")], default="NORMAL", max_length=10)),
                ("estado", models.CharField(choices=[("PROGRAMADA", "Programada"), ("EN_CURSO", "En curso"), ("FINALIZADA", "Finalizada"), ("CANCELADA", "Cancelada")], default="PROGRAMADA", max_length=12)),
                ("chofer", models.CharField(blank=True, default="", max_length=80, verbose_name="chofer")),
                ("recorrido", models.CharField(blank=True, default="", max_length=120, verbose_name="recorrido")),
                ("nota", models.CharField(blank=True, default="", max_length=160, verbose_name="nota")),
                ("colectivo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="salidas_programadas", to="flota.colectivo")),
            ],
            options={
                "ordering": ["salida_programada", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="salidaprogramada",
            index=models.Index(fields=["salida_programada"], name="idx_salida_prog_fecha"),
        ),
        migrations.AddIndex(
            model_name="salidaprogramada",
            index=models.Index(fields=["colectivo", "salida_programada"], name="idx_salida_prog_colectivo"),
        ),
    ]
