# Generated by Django 5.1.15 on 2026-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ubicacion_tipo_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
