# Generated by Django 5.1.15 on 2026-02-24 05:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientostock_colectivo_safe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['codigo'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='stockactual',
            options={'verbose_name': 'stock actual', 'verbose_name_plural': 'stock actual'},
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='idx_mov_destino_fecha',
        ),
        migrations.RemoveIndex(
            model_name='ubicacion',
            name='idx_ubicacion_nombre',
        ),

        # IMPORTANTE:
        # 0004_ubicacion_layout_safe agrega columnas (padre/pasillo/modulo/nivel/posicion/permite_transferencias)
        # vía SQL "safe". En instalaciones nuevas (incl. DB de tests), ejecutar AddField acá produce
        # "duplicate column". Por eso, en 0006 reflejamos los campos SOLO en el estado de migraciones.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='ubicacion',
                    name='modulo',
                    field=models.SmallIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='ubicacion',
                    name='nivel',
                    field=models.SmallIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='ubicacion',
                    name='padre',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='inventario.ubicacion'),
                ),
                migrations.AddField(
                    model_name='ubicacion',
                    name='pasillo',
                    field=models.CharField(blank=True, default='', max_length=20),
                ),
                migrations.AddField(
                    model_name='ubicacion',
                    name='permite_transferencias',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='ubicacion',
                    name='posicion',
                    field=models.SmallIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='stockactual',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(help_text='Código único. Ej: DP-A01-M01-N01-P01', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('DEPOSITO', 'Depósito'), ('UBICACION', 'Ubicación'), ('ZONA', 'Zona'), ('OTRO', 'Otro')], default='UBICACION', max_length=14),
        ),
    ]
