# Generated by ChatGPT for La Termal ERP

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(blank=True, db_index=True, max_length=150)),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("view_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("app_area", models.CharField(blank=True, db_index=True, max_length=50)),
                ("action", models.CharField(blank=True, db_index=True, max_length=50)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de auditoría",
                "verbose_name_plural": "Eventos de auditoría",
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["created_at", "username"], name="auditoria_a_created__2f8a7a_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["created_at", "app_area"], name="auditoria_a_created__f28af0_idx"),
        ),
    ]
