# Generated by Django 5.1.15 on 2026-03-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='auditoria_a_created_99daf2_idx',
            old_name='auditoria_a_created__2f8a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='auditoria_a_created_ac82c6_idx',
            old_name='auditoria_a_created__f28af0_idx',
        ),
    ]
