# Generated by Django 5.1.15 on 2026-02-19 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('action', models.CharField(max_length=80, verbose_name='acción')),
                ('entity', models.CharField(max_length=80, verbose_name='entidad')),
                ('entity_id', models.CharField(blank=True, max_length=80, verbose_name='id entidad')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'log de auditoría',
                'verbose_name_plural': 'logs de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
