# Generated by Django 5.1.15 on 2026-02-23 19:58

import adjuntos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_movimientostock_colectivo_safe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to=adjuntos.models.producto_imagen_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['producto', 'orden'], name='adjuntos_pr_product_df9369_idx')],
            },
        ),
    ]

